name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests with coverage
      run: bundle exec rake test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/.resultset.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Run RuboCop
      run: bundle exec rubocop --format github

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Run bundle audit
      run: |
        gem install bundler-audit
        bundle audit --update

    - name: Run Brakeman security scan
      run: |
        gem install brakeman
        brakeman --no-pager --format github || true

  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Build gem
      run: bundle exec rake build

    - name: Upload gem artifact
      uses: actions/upload-artifact@v4
      with:
        name: gem-${{ github.sha }}
        path: pkg/*.gem
        retention-days: 30
